/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameDatabase;

/**
 *
 * @author Chris
 */
public class IndividualResultFrame extends javax.swing.JFrame {

    SQLController controller;
    
    /**
     * Creates new form IndividualResultFrame
     */
    public IndividualResultFrame(SQLController controller, Record record) {
        initComponents();
        this.controller = controller;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        if (record == null)
            System.out.println("record = null");
        ResultTitleTextField.setText(record.title);
        ResultPlatformTextField.setText(record.platform);
        ResultYearOfReleaseTextField.setText(record.yearOfRelease);
        ResultGenreTextField.setText(record.genre);
        ResultDeveloperTextField.setText(record.developer);
        ResultPublisherTextField.setText(record.publisher);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IndividualResultsTitleLabel = new javax.swing.JLabel();
        IndividualResultsPlatformLabel = new javax.swing.JLabel();
        IndividualResultsYearOfReleaseLabel = new javax.swing.JLabel();
        IndividualResultsGenreLabel = new javax.swing.JLabel();
        ResultYearOfReleaseTextField = new javax.swing.JTextField();
        ResultPlatformTextField = new javax.swing.JTextField();
        ResultTitleTextField = new javax.swing.JTextField();
        ResultGenreTextField = new javax.swing.JTextField();
        IndividualResultsMessagelabel = new javax.swing.JLabel();
        IndividualResultsUpdateButton = new javax.swing.JButton();
        IndividialResultsCancelButton = new javax.swing.JButton();
        IndividualResultsDeveloperLabel = new javax.swing.JLabel();
        IndividualResultsPublisherLabel = new javax.swing.JLabel();
        ResultDeveloperTextField = new javax.swing.JTextField();
        ResultPublisherTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IndividualResultsTitleLabel.setText("Title:");

        IndividualResultsPlatformLabel.setText("Platform:");

        IndividualResultsYearOfReleaseLabel.setText("Year of Release:");

        IndividualResultsGenreLabel.setText("Genre:");

        IndividualResultsUpdateButton.setText("Update");

        IndividialResultsCancelButton.setText("Cancel");
        IndividialResultsCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndividialResultsCancelButtonActionPerformed(evt);
            }
        });

        IndividualResultsDeveloperLabel.setText("Developer:");

        IndividualResultsPublisherLabel.setText("Publisher:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IndividualResultsMessagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IndividualResultsGenreLabel)
                                        .addComponent(IndividualResultsDeveloperLabel)
                                        .addComponent(IndividualResultsPublisherLabel)
                                        .addComponent(IndividualResultsYearOfReleaseLabel))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ResultDeveloperTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ResultGenreTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ResultYearOfReleaseTextField)
                                        .addComponent(ResultPublisherTextField)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IndividualResultsPlatformLabel)
                                        .addComponent(IndividualResultsTitleLabel))
                                    .addGap(67, 67, 67)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ResultTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ResultPlatformTextField))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IndividualResultsUpdateButton)
                                .addGap(18, 18, 18)
                                .addComponent(IndividialResultsCancelButton)))
                        .addGap(0, 237, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsTitleLabel)
                    .addComponent(ResultTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsPlatformLabel)
                    .addComponent(ResultPlatformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsYearOfReleaseLabel)
                    .addComponent(ResultYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsGenreLabel)
                    .addComponent(ResultGenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsDeveloperLabel)
                    .addComponent(ResultDeveloperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsPublisherLabel)
                    .addComponent(ResultPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsUpdateButton)
                    .addComponent(IndividialResultsCancelButton))
                .addGap(106, 106, 106)
                .addComponent(IndividualResultsMessagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IndividialResultsCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndividialResultsCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IndividialResultsCancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IndividialResultsCancelButton;
    private javax.swing.JLabel IndividualResultsDeveloperLabel;
    private javax.swing.JLabel IndividualResultsGenreLabel;
    private javax.swing.JLabel IndividualResultsMessagelabel;
    private javax.swing.JLabel IndividualResultsPlatformLabel;
    private javax.swing.JLabel IndividualResultsPublisherLabel;
    private javax.swing.JLabel IndividualResultsTitleLabel;
    private javax.swing.JButton IndividualResultsUpdateButton;
    private javax.swing.JLabel IndividualResultsYearOfReleaseLabel;
    private javax.swing.JTextField ResultDeveloperTextField;
    private javax.swing.JTextField ResultGenreTextField;
    private javax.swing.JTextField ResultPlatformTextField;
    private javax.swing.JTextField ResultPublisherTextField;
    private javax.swing.JTextField ResultTitleTextField;
    private javax.swing.JTextField ResultYearOfReleaseTextField;
    // End of variables declaration//GEN-END:variables
}