/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameDatabase;

/**
 *
 * @author Chris
 */
public class IndividualResultFrame extends javax.swing.JFrame {

    /**
     * Creates new form IndividualResultFrame
     */
    public IndividualResultFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IndividualResultsTitleLabel = new javax.swing.JLabel();
        IndividualResultsPlatformLabel = new javax.swing.JLabel();
        IndividualResultsYearOfReleaseLabel = new javax.swing.JLabel();
        IndividualResultsGenreLabel = new javax.swing.JLabel();
        IndividualResultsYearOfReleaseTextField = new javax.swing.JTextField();
        IndividualResultsPlatformTextField = new javax.swing.JTextField();
        IndividualResultsTitleTextField = new javax.swing.JTextField();
        IndividualResultsGenreTextField = new javax.swing.JTextField();
        IndividualResultsMessagelabel = new javax.swing.JLabel();
        IndividualResultsUpdateButton = new javax.swing.JButton();
        IndividialResultsCancelButton = new javax.swing.JButton();
        IndividualResultsDeveloperLabel = new javax.swing.JLabel();
        IndividualResultsPublisherLabel = new javax.swing.JLabel();
        IndividualResultsDeveloperTextField = new javax.swing.JTextField();
        IndividualResultsPublisherTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IndividualResultsTitleLabel.setText("Title:");

        IndividualResultsPlatformLabel.setText("Platform:");

        IndividualResultsYearOfReleaseLabel.setText("Year of Release:");

        IndividualResultsGenreLabel.setText("Genre:");

        IndividualResultsUpdateButton.setText("Update");

        IndividialResultsCancelButton.setText("Cancel");
        IndividialResultsCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndividialResultsCancelButtonActionPerformed(evt);
            }
        });

        IndividualResultsDeveloperLabel.setText("Developer:");

        IndividualResultsPublisherLabel.setText("Publisher:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IndividualResultsMessagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(IndividualResultsYearOfReleaseLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(IndividualResultsYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(IndividualResultsTitleLabel)
                                    .addGap(96, 96, 96)
                                    .addComponent(IndividualResultsTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(IndividualResultsPlatformLabel)
                                    .addGap(67, 67, 67)
                                    .addComponent(IndividualResultsPlatformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IndividualResultsGenreLabel)
                                        .addComponent(IndividualResultsDeveloperLabel)
                                        .addComponent(IndividualResultsPublisherLabel))
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IndividualResultsGenreTextField)
                                        .addComponent(IndividualResultsDeveloperTextField)
                                        .addComponent(IndividualResultsPublisherTextField))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IndividualResultsUpdateButton)
                                .addGap(18, 18, 18)
                                .addComponent(IndividialResultsCancelButton)))
                        .addGap(0, 237, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsTitleLabel)
                    .addComponent(IndividualResultsTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsPlatformLabel)
                    .addComponent(IndividualResultsPlatformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsYearOfReleaseLabel)
                    .addComponent(IndividualResultsYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsGenreLabel)
                    .addComponent(IndividualResultsGenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsDeveloperLabel)
                    .addComponent(IndividualResultsDeveloperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsPublisherLabel)
                    .addComponent(IndividualResultsPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsUpdateButton)
                    .addComponent(IndividialResultsCancelButton))
                .addGap(106, 106, 106)
                .addComponent(IndividualResultsMessagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IndividialResultsCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndividialResultsCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IndividialResultsCancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndividualResultFrame().setVisible(true);;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IndividialResultsCancelButton;
    private javax.swing.JLabel IndividualResultsDeveloperLabel;
    private javax.swing.JTextField IndividualResultsDeveloperTextField;
    private javax.swing.JLabel IndividualResultsGenreLabel;
    private javax.swing.JTextField IndividualResultsGenreTextField;
    private javax.swing.JLabel IndividualResultsMessagelabel;
    private javax.swing.JLabel IndividualResultsPlatformLabel;
    private javax.swing.JTextField IndividualResultsPlatformTextField;
    private javax.swing.JLabel IndividualResultsPublisherLabel;
    private javax.swing.JTextField IndividualResultsPublisherTextField;
    private javax.swing.JLabel IndividualResultsTitleLabel;
    private javax.swing.JTextField IndividualResultsTitleTextField;
    private javax.swing.JButton IndividualResultsUpdateButton;
    private javax.swing.JLabel IndividualResultsYearOfReleaseLabel;
    private javax.swing.JTextField IndividualResultsYearOfReleaseTextField;
    // End of variables declaration//GEN-END:variables
}