/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameDatabase;

import javax.swing.JOptionPane;

/**
 *
 * @author Chris
 */
public class IndividualResultFrame extends javax.swing.JFrame {

    SQLController controller;
    ResultsFrame results;
    
    /**
     * Creates new form IndividualResultFrame
     */
    public IndividualResultFrame(SQLController controller, Record record, ResultsFrame results) {
        initComponents();
        this.controller = controller;
        this.results = results;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        if (record == null)
            System.out.println("record = null");
        ResultTitleTextField.setText(record.title);
        ResultPlatformTextField.setText(record.platform);
        ResultYearOfReleaseTextField.setText(record.yearOfRelease);
        ResultGenreTextField.setText(record.genre);
        ResultDeveloperTextField.setText(record.developer);
        ResultPublisherTextField.setText(record.publisher);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IndividualResultsTitleLabel = new javax.swing.JLabel();
        IndividualResultsPlatformLabel = new javax.swing.JLabel();
        IndividualResultsYearOfReleaseLabel = new javax.swing.JLabel();
        IndividualResultsGenreLabel = new javax.swing.JLabel();
        ResultYearOfReleaseTextField = new javax.swing.JTextField();
        ResultPlatformTextField = new javax.swing.JTextField();
        ResultTitleTextField = new javax.swing.JTextField();
        ResultGenreTextField = new javax.swing.JTextField();
        ResultMessageLabel = new javax.swing.JLabel();
        IndividualResultsUpdateButton = new javax.swing.JButton();
        IndividualResultsDeveloperLabel = new javax.swing.JLabel();
        IndividualResultsPublisherLabel = new javax.swing.JLabel();
        ResultDeveloperTextField = new javax.swing.JTextField();
        ResultPublisherTextField = new javax.swing.JTextField();
        ResultYearOfReleaseErrorLabel = new javax.swing.JLabel();
        ResultOKButton = new javax.swing.JButton();
        ResultDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IndividualResultsTitleLabel.setText("Title:");

        IndividualResultsPlatformLabel.setText("Platform:");

        IndividualResultsYearOfReleaseLabel.setText("Year of Release:");

        IndividualResultsGenreLabel.setText("Genre:");

        ResultPlatformTextField.setEditable(false);

        ResultTitleTextField.setEditable(false);

        IndividualResultsUpdateButton.setText("Update");
        IndividualResultsUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndividualResultsUpdateButtonActionPerformed(evt);
            }
        });

        IndividualResultsDeveloperLabel.setText("Developer:");

        IndividualResultsPublisherLabel.setText("Publisher:");

        ResultOKButton.setText("OK");
        ResultOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultOKButtonActionPerformed(evt);
            }
        });

        ResultDeleteButton.setText("Delete Record");
        ResultDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IndividualResultsUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResultOKButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IndividualResultsGenreLabel)
                                    .addComponent(IndividualResultsDeveloperLabel)
                                    .addComponent(IndividualResultsPublisherLabel)
                                    .addComponent(IndividualResultsYearOfReleaseLabel))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResultDeveloperTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ResultGenreTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ResultYearOfReleaseTextField)
                                    .addComponent(ResultPublisherTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IndividualResultsPlatformLabel)
                                    .addComponent(IndividualResultsTitleLabel))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResultTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResultPlatformTextField))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResultYearOfReleaseErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 118, Short.MAX_VALUE)
                                .addComponent(ResultDeleteButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsTitleLabel)
                    .addComponent(ResultTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultDeleteButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsPlatformLabel)
                    .addComponent(ResultPlatformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsYearOfReleaseLabel)
                    .addComponent(ResultYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultYearOfReleaseErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsGenreLabel)
                    .addComponent(ResultGenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsDeveloperLabel)
                    .addComponent(ResultDeveloperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsPublisherLabel)
                    .addComponent(ResultPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualResultsUpdateButton)
                    .addComponent(ResultOKButton))
                .addGap(106, 106, 106)
                .addComponent(ResultMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IndividualResultsUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndividualResultsUpdateButtonActionPerformed
        // TODO add your handling code here:
        String title = ResultTitleTextField.getText().trim();
        String platform = ResultPlatformTextField.getText().trim();
        String genre = ResultGenreTextField.getText().trim();
        String developer = ResultDeveloperTextField.getText().trim();
        String publisher = ResultPublisherTextField.getText().trim();
        String yearOfRelease = ResultYearOfReleaseTextField.getText().trim();
        
        if (yearOfRelease.equals("")) {
            // do nothing
        } else if (yearOfRelease.length() != 4) {
            ResultYearOfReleaseErrorLabel.setText("Error: Year must be 4 numbers");
            return;
        } else {
            int year;
            try {
                year = Integer.parseInt(yearOfRelease);
            } catch (NumberFormatException e) {
                ResultYearOfReleaseErrorLabel.setText("Error: Year must be 4 numbers");
                return;
            }
        }
        
        String message = controller.updateGame(title, platform, developer, publisher, yearOfRelease, genre);
        ResultMessageLabel.setText(message);
    }//GEN-LAST:event_IndividualResultsUpdateButtonActionPerformed

    private void ResultOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultOKButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ResultOKButtonActionPerformed

    private void ResultDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultDeleteButtonActionPerformed
        // TODO add your handling code here:
        String title = ResultTitleTextField.getText().trim();
        String platform = ResultPlatformTextField.getText().trim();
        controller.removeRecord(title, platform);
        JOptionPane.showMessageDialog(this, "Record removed");
        results.dispose();
        dispose();
    }//GEN-LAST:event_ResultDeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IndividualResultsDeveloperLabel;
    private javax.swing.JLabel IndividualResultsGenreLabel;
    private javax.swing.JLabel IndividualResultsPlatformLabel;
    private javax.swing.JLabel IndividualResultsPublisherLabel;
    private javax.swing.JLabel IndividualResultsTitleLabel;
    private javax.swing.JButton IndividualResultsUpdateButton;
    private javax.swing.JLabel IndividualResultsYearOfReleaseLabel;
    private javax.swing.JButton ResultDeleteButton;
    private javax.swing.JTextField ResultDeveloperTextField;
    private javax.swing.JTextField ResultGenreTextField;
    private javax.swing.JLabel ResultMessageLabel;
    private javax.swing.JButton ResultOKButton;
    private javax.swing.JTextField ResultPlatformTextField;
    private javax.swing.JTextField ResultPublisherTextField;
    private javax.swing.JTextField ResultTitleTextField;
    private javax.swing.JLabel ResultYearOfReleaseErrorLabel;
    private javax.swing.JTextField ResultYearOfReleaseTextField;
    // End of variables declaration//GEN-END:variables
}