package GameDatabase;

import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    SQLController controller;

    /**
     * Creates new form TabedMenuFrame
     */
    public Main() {
        initComponents();
        controller = new SQLController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuTabPanel = new javax.swing.JTabbedPane();
        SearchTabPanel = new javax.swing.JPanel();
        SearchTitleLabel = new javax.swing.JLabel();
        SearchPlatformLabel = new javax.swing.JLabel();
        SearchYearOfReleaseLabel = new javax.swing.JLabel();
        SearchGenreLabel = new javax.swing.JLabel();
        SearchYearOfReleaseTextField = new javax.swing.JTextField();
        SearchPlatformTextField = new javax.swing.JTextField();
        SearchTitleTextField = new javax.swing.JTextField();
        SearchGenreTextField = new javax.swing.JTextField();
        SearchMessageLabel = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        SearchDeveloperLabel = new javax.swing.JLabel();
        SearchDeveloperTextField = new javax.swing.JTextField();
        SearchPublisherLabel = new javax.swing.JLabel();
        SearchPublisherTextField = new javax.swing.JTextField();
        SearchYearOfReleaseErrorLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        SearchCompanyNameLabel = new javax.swing.JLabel();
        SearchCompanyLocationLabel = new javax.swing.JLabel();
        SearchCompanyMessageLabel = new javax.swing.JLabel();
        SearchCompanyLocationTextField = new javax.swing.JTextField();
        SearchCompanyNameTextField = new javax.swing.JTextField();
        SearchCompanyButton = new javax.swing.JButton();
        SearchCompanyExitButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SearchPlatformNameLabel = new javax.swing.JLabel();
        SearchPlatformYORLabel = new javax.swing.JLabel();
        SearchPlatformNameTextField = new javax.swing.JTextField();
        SearchPlatformYORTextField = new javax.swing.JTextField();
        SearchPlatformMessageLabel = new javax.swing.JLabel();
        SearchPlatformButton = new javax.swing.JButton();
        SearchPlatformExitButton = new javax.swing.JButton();
        AddCompanyPanel = new javax.swing.JPanel();
        CompanyNameLabel = new javax.swing.JLabel();
        CompanyLocationLabel = new javax.swing.JLabel();
        CompanyNameTextField = new javax.swing.JTextField();
        CompanyLocationTextField = new javax.swing.JTextField();
        AddCompanyConfirmButton = new javax.swing.JButton();
        AddCompanyClearButton = new javax.swing.JButton();
        AddCompanyExitButton = new javax.swing.JButton();
        CompanyNameErrorLabel = new javax.swing.JLabel();
        CompanyLocationErrorLabel = new javax.swing.JLabel();
        AddCompanyMessageLabel = new javax.swing.JLabel();
        AddPlatformTabPanel = new javax.swing.JPanel();
        PlatformNameLabel = new javax.swing.JLabel();
        PlatformYearOfReleaseLabel = new javax.swing.JLabel();
        PlatformNameTextField = new javax.swing.JTextField();
        PlatformYearOfReleaseTextField = new javax.swing.JTextField();
        AddPlatformConfirmButton = new javax.swing.JButton();
        AddPlatformClearButton = new javax.swing.JButton();
        AddPlatformExitButton = new javax.swing.JButton();
        PlatformNameErrorLabel = new javax.swing.JLabel();
        PlatformYearOfReleaseErrorLabel = new javax.swing.JLabel();
        AddPlatformMessageLabel = new javax.swing.JLabel();
        AddGameTabPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        PlatformLabel = new javax.swing.JLabel();
        YearOfReleaseLabel = new javax.swing.JLabel();
        GenreLabel = new javax.swing.JLabel();
        GameTitleTextField = new javax.swing.JTextField();
        GamePlatformTextField = new javax.swing.JTextField();
        GameYearOfReleaseTextField = new javax.swing.JTextField();
        GameGenreTextField = new javax.swing.JTextField();
        AddGameConfirmButton = new javax.swing.JButton();
        AddGameClearButton = new javax.swing.JButton();
        AddGameExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GameDeveloperTextField = new javax.swing.JTextField();
        GamePublisherTextField = new javax.swing.JTextField();
        GameTitleErrorLabel = new javax.swing.JLabel();
        GamePlatformErrorLabel = new javax.swing.JLabel();
        GameYearOfReleaseErrorLabel = new javax.swing.JLabel();
        GameGenreErrorLabel = new javax.swing.JLabel();
        GameDeveloperErrorLabel = new javax.swing.JLabel();
        GamePublisherErrorLabel = new javax.swing.JLabel();
        AddGameMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Game Database");

        SearchTitleLabel.setText("Title:");

        SearchPlatformLabel.setText("Platform:");

        SearchYearOfReleaseLabel.setText("Year of Release:");

        SearchGenreLabel.setText("Genre:");

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        SearchDeveloperLabel.setText("Developer:");

        SearchPublisherLabel.setText("Publisher:");

        javax.swing.GroupLayout SearchTabPanelLayout = new javax.swing.GroupLayout(SearchTabPanel);
        SearchTabPanel.setLayout(SearchTabPanelLayout);
        SearchTabPanelLayout.setHorizontalGroup(
            SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SearchTabPanelLayout.createSequentialGroup()
                        .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SearchTabPanelLayout.createSequentialGroup()
                                .addComponent(SearchButton)
                                .addGap(18, 18, 18)
                                .addComponent(ExitButton))
                            .addGroup(SearchTabPanelLayout.createSequentialGroup()
                                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchYearOfReleaseLabel)
                                    .addComponent(SearchPlatformLabel)
                                    .addComponent(SearchTitleLabel)
                                    .addComponent(SearchGenreLabel)
                                    .addComponent(SearchDeveloperLabel)
                                    .addComponent(SearchPublisherLabel))
                                .addGap(18, 18, 18)
                                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SearchYearOfReleaseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchPlatformTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchTitleTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchGenreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(SearchDeveloperTextField)
                                    .addComponent(SearchPublisherTextField))))
                        .addGap(18, 18, 18)
                        .addComponent(SearchYearOfReleaseErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SearchTabPanelLayout.setVerticalGroup(
            SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTitleLabel)
                    .addComponent(SearchTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchPlatformLabel)
                    .addComponent(SearchPlatformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchYearOfReleaseLabel)
                    .addComponent(SearchYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchYearOfReleaseErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchGenreLabel)
                    .addComponent(SearchGenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchDeveloperLabel)
                    .addComponent(SearchDeveloperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchPublisherLabel)
                    .addComponent(SearchPublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(ExitButton))
                .addGap(53, 53, 53)
                .addComponent(SearchMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainMenuTabPanel.addTab("Search by Game", SearchTabPanel);

        SearchCompanyNameLabel.setText("Name:");

        SearchCompanyLocationLabel.setText("Location:");

        SearchCompanyButton.setText("Search");

        SearchCompanyExitButton.setText("Exit");
        SearchCompanyExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCompanyExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchCompanyMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchCompanyLocationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(SearchCompanyLocationTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchCompanyNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(SearchCompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(192, 192, 192))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchCompanyButton)
                        .addGap(18, 18, 18)
                        .addComponent(SearchCompanyExitButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCompanyNameLabel)
                    .addComponent(SearchCompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCompanyLocationLabel)
                    .addComponent(SearchCompanyLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCompanyButton)
                    .addComponent(SearchCompanyExitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(SearchCompanyMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainMenuTabPanel.addTab("Search by Company", jPanel1);

        SearchPlatformNameLabel.setText("Name:");

        SearchPlatformYORLabel.setText("Year of Release:");

        SearchPlatformButton.setText("Search");

        SearchPlatformExitButton.setText("Exit");
        SearchPlatformExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPlatformExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchPlatformMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchPlatformYORLabel)
                                    .addComponent(SearchPlatformNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SearchPlatformNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(SearchPlatformYORTextField)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SearchPlatformButton)
                                .addGap(18, 18, 18)
                                .addComponent(SearchPlatformExitButton)))
                        .addGap(0, 142, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchPlatformNameLabel)
                    .addComponent(SearchPlatformNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchPlatformYORLabel)
                    .addComponent(SearchPlatformYORTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchPlatformButton)
                    .addComponent(SearchPlatformExitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(SearchPlatformMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainMenuTabPanel.addTab("Search by Platform", jPanel2);

        CompanyNameLabel.setText("Name:");

        CompanyLocationLabel.setText("Location:");

        CompanyNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyNameTextFieldActionPerformed(evt);
            }
        });

        CompanyLocationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyLocationTextFieldActionPerformed(evt);
            }
        });

        AddCompanyConfirmButton.setText("Confirm");
        AddCompanyConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCompanyConfirmButtonActionPerformed(evt);
            }
        });

        AddCompanyClearButton.setText("Clear");
        AddCompanyClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCompanyClearButtonActionPerformed(evt);
            }
        });

        AddCompanyExitButton.setText("Exit");
        AddCompanyExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCompanyExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCompanyPanelLayout = new javax.swing.GroupLayout(AddCompanyPanel);
        AddCompanyPanel.setLayout(AddCompanyPanelLayout);
        AddCompanyPanelLayout.setHorizontalGroup(
            AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddCompanyMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                        .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                                .addGap(0, 62, Short.MAX_VALUE)
                                .addComponent(AddCompanyConfirmButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddCompanyClearButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddCompanyExitButton))
                            .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CompanyLocationLabel)
                                    .addComponent(CompanyNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CompanyNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(CompanyLocationTextField))))
                        .addGap(18, 18, 18)
                        .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CompanyNameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CompanyLocationErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap())
        );
        AddCompanyPanelLayout.setVerticalGroup(
            AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CompanyNameErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CompanyNameLabel)
                        .addComponent(CompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CompanyLocationErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CompanyLocationLabel)
                        .addComponent(CompanyLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCompanyConfirmButton)
                    .addComponent(AddCompanyClearButton)
                    .addComponent(AddCompanyExitButton))
                .addGap(156, 156, 156)
                .addComponent(AddCompanyMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainMenuTabPanel.addTab("Add Company", AddCompanyPanel);

        PlatformNameLabel.setText("Name:");

        PlatformYearOfReleaseLabel.setText("Year of Release:");

        AddPlatformConfirmButton.setText("Confirm");
        AddPlatformConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatformConfirmButtonActionPerformed(evt);
            }
        });

        AddPlatformClearButton.setText("Clear");
        AddPlatformClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatformClearButtonActionPerformed(evt);
            }
        });

        AddPlatformExitButton.setText("Exit");
        AddPlatformExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatformExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPlatformTabPanelLayout = new javax.swing.GroupLayout(AddPlatformTabPanel);
        AddPlatformTabPanel.setLayout(AddPlatformTabPanelLayout);
        AddPlatformTabPanelLayout.setHorizontalGroup(
            AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                        .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                                .addComponent(AddPlatformConfirmButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddPlatformClearButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddPlatformExitButton))
                            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PlatformYearOfReleaseLabel)
                                    .addComponent(PlatformNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PlatformNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(PlatformYearOfReleaseTextField))))
                        .addGap(18, 18, 18)
                        .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlatformNameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PlatformYearOfReleaseErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addComponent(AddPlatformMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AddPlatformTabPanelLayout.setVerticalGroup(
            AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlatformNameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PlatformNameLabel)
                        .addComponent(PlatformNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlatformYearOfReleaseErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PlatformYearOfReleaseLabel)
                        .addComponent(PlatformYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddPlatformConfirmButton)
                    .addComponent(AddPlatformClearButton)
                    .addComponent(AddPlatformExitButton))
                .addGap(159, 159, 159)
                .addComponent(AddPlatformMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainMenuTabPanel.addTab("Add Platform", AddPlatformTabPanel);

        TitleLabel.setText("Title:");

        PlatformLabel.setText("Platform:");

        YearOfReleaseLabel.setText("Year of Release:");

        GenreLabel.setText("Genre:");

        AddGameConfirmButton.setText("Confirm");
        AddGameConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGameConfirmButtonActionPerformed(evt);
            }
        });

        AddGameClearButton.setText("Clear");
        AddGameClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGameClearButtonActionPerformed(evt);
            }
        });

        AddGameExitButton.setText("Exit");
        AddGameExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGameExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Developer:");

        jLabel2.setText("Publisher:");

        javax.swing.GroupLayout AddGameTabPanelLayout = new javax.swing.GroupLayout(AddGameTabPanel);
        AddGameTabPanel.setLayout(AddGameTabPanelLayout);
        AddGameTabPanelLayout.setHorizontalGroup(
            AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddGameMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                                .addComponent(AddGameConfirmButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddGameClearButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddGameExitButton))
                            .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(YearOfReleaseLabel)
                                    .addComponent(GenreLabel)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GameGenreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(GameYearOfReleaseTextField)
                                    .addComponent(GameDeveloperTextField)
                                    .addComponent(GamePublisherTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddGameTabPanelLayout.createSequentialGroup()
                                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TitleLabel)
                                    .addComponent(PlatformLabel))
                                .addGap(67, 67, 67)
                                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GamePlatformTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(GameTitleTextField))))
                        .addGap(18, 18, 18)
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GameTitleErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GamePlatformErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GameYearOfReleaseErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GameGenreErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GameDeveloperErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GamePublisherErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                .addContainerGap())
        );
        AddGameTabPanelLayout.setVerticalGroup(
            AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GameTitleErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TitleLabel)
                        .addComponent(GameTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GamePlatformErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PlatformLabel)
                        .addComponent(GamePlatformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GameYearOfReleaseErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(YearOfReleaseLabel)
                        .addComponent(GameYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GameGenreErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GenreLabel)
                        .addComponent(GameGenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GameDeveloperErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(GameDeveloperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GamePublisherErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(GamePublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddGameConfirmButton)
                    .addComponent(AddGameClearButton)
                    .addComponent(AddGameExitButton))
                .addGap(18, 18, 18)
                .addComponent(AddGameMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainMenuTabPanel.addTab("Add Game", AddGameTabPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuTabPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuTabPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddGameExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGameExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_AddGameExitButtonActionPerformed

    private void AddGameClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGameClearButtonActionPerformed
        // TODO add your handling code here:
        GameTitleTextField.setText("");
        GamePlatformTextField.setText("");
        GameYearOfReleaseTextField.setText("");
        GameGenreTextField.setText("");
        GameDeveloperTextField.setText("");
        GamePublisherTextField.setText("");
        GameTitleErrorLabel.setText("");
        GamePlatformErrorLabel.setText("");
        GameYearOfReleaseErrorLabel.setText("");
        GameGenreErrorLabel.setText("");
        GameDeveloperErrorLabel.setText("");
        GamePublisherErrorLabel.setText("");
        AddGameMessageLabel.setText("");
    }//GEN-LAST:event_AddGameClearButtonActionPerformed

    private void AddGameConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGameConfirmButtonActionPerformed
        // TODO add your handling code here:
        String name = GameTitleTextField.getText().trim();
        if (name.equals("")) {
            GameTitleErrorLabel.setText("required field");
        }

        String platform = GamePlatformTextField.getText();
        if (platform.equals("")) {
            GamePlatformErrorLabel.setText("required field");
        }

        String genre = GameGenreTextField.getText().trim();
        String developer = GameDeveloperTextField.getText().trim();
        String publisher = GamePublisherTextField.getText().trim();

        String yearOfRelease = GameYearOfReleaseTextField.getText().trim();
        if (yearOfRelease.equals("")) {
            yearOfRelease = "NULL";
        } else if (yearOfRelease.length() != 4) {
            GameYearOfReleaseErrorLabel.setText("Error: Year must be 4 numbers");
            return;
        } else {
            int year;
            try {
                year = Integer.parseInt(yearOfRelease);
            } catch (NumberFormatException e) {
                GameYearOfReleaseErrorLabel.setText("Error: Year must be 4 numbers");
                return;
            }
        }

        if (!name.equals("") && !platform.equals("")) {
            String message = controller.addGame(name, platform, developer, publisher, yearOfRelease, genre);
            AddGameMessageLabel.setText(message);
        }
    }//GEN-LAST:event_AddGameConfirmButtonActionPerformed

    private void AddPlatformExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatformExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_AddPlatformExitButtonActionPerformed

    private void AddPlatformClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatformClearButtonActionPerformed
        // TODO add your handling code here:
        PlatformNameTextField.setText("");
        PlatformYearOfReleaseTextField.setText("");
        PlatformNameErrorLabel.setText("");
        PlatformYearOfReleaseErrorLabel.setText("");
        AddPlatformMessageLabel.setText("");
    }//GEN-LAST:event_AddPlatformClearButtonActionPerformed

    private void AddPlatformConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatformConfirmButtonActionPerformed
        // TODO add your handling code here:
        String name = PlatformNameTextField.getText().trim();

        if (name.equals("")) {
            PlatformNameErrorLabel.setText("required field");
        }

        String yearOfRelease = PlatformYearOfReleaseTextField.getText().trim();
        if (yearOfRelease.equals("")) {
            yearOfRelease = "NULL";
        } else if (yearOfRelease.length() != 4) {
            PlatformYearOfReleaseErrorLabel.setText("Error: Year must be 4 numbers");
            return;
        } else {
            int year;
            try {
                year = Integer.parseInt(yearOfRelease);
            } catch (NumberFormatException e) {
                PlatformYearOfReleaseErrorLabel.setText("Error: Year must be 4 numbers");
                return;
            }
        }

        if (!name.equals("")) {
            String message = controller.addPlatform(name, yearOfRelease);
            AddPlatformMessageLabel.setText(message);

            if (message.equals("Successful entry")) {
                PlatformNameTextField.setText("");
                PlatformYearOfReleaseTextField.setText("");
                PlatformNameErrorLabel.setText("");
                PlatformYearOfReleaseErrorLabel.setText("");
            }
        }
    }//GEN-LAST:event_AddPlatformConfirmButtonActionPerformed

    private void AddCompanyExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCompanyExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_AddCompanyExitButtonActionPerformed

    private void AddCompanyClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCompanyClearButtonActionPerformed
        // TODO add your handling code here:
        CompanyNameTextField.setText("");
        CompanyLocationTextField.setText("");
        CompanyNameErrorLabel.setText("");
        CompanyLocationErrorLabel.setText("");
        AddCompanyMessageLabel.setText("");
    }//GEN-LAST:event_AddCompanyClearButtonActionPerformed

    private void AddCompanyConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCompanyConfirmButtonActionPerformed
        // TODO add your handling code here:
        String name = CompanyNameTextField.getText().trim();
        String location = CompanyLocationTextField.getText().trim();

        if (name.equals("")) {
            CompanyNameErrorLabel.setText("required field");
        }

        if (location.equals("")) {
            CompanyLocationErrorLabel.setText("required field");
        }

        if (!name.equals("") && !location.equals("")) {
            String message = controller.addCompany(name, location);
            AddCompanyMessageLabel.setText(message);

            if (message.equals("Successful entry")) {
                CompanyNameTextField.setText("");
                CompanyLocationTextField.setText("");
                CompanyNameErrorLabel.setText("");
                CompanyLocationErrorLabel.setText("");
            }
        }
    }//GEN-LAST:event_AddCompanyConfirmButtonActionPerformed

    private void CompanyLocationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyLocationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyLocationTextFieldActionPerformed

    private void CompanyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyNameTextFieldActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String title = SearchTitleTextField.getText().trim();
        String platform = SearchPlatformTextField.getText().trim();
        String genre = SearchGenreTextField.getText().trim();
        String developer = SearchDeveloperTextField.getText().trim();
        String publisher = SearchPublisherTextField.getText().trim();
        String yearOfRelease = SearchYearOfReleaseTextField.getText().trim();

        if (yearOfRelease.equals("")) {
            // do nothing
        } else if (yearOfRelease.length() != 4) {
            SearchYearOfReleaseErrorLabel.setText("Error: Year must be 4 numbers");
            return;
        } else {
            int year;
            try {
                year = Integer.parseInt(yearOfRelease);
            } catch (NumberFormatException e) {
                GameYearOfReleaseErrorLabel.setText("Error: Year must be 4 numbers");
                return;
            }
        }

        DefaultTableModel model = controller.searchForGame(title, platform, developer, publisher, yearOfRelease, genre);
        new ResultsFrame(controller, model).setVisible(true);
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SearchCompanyExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCompanyExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SearchCompanyExitButtonActionPerformed

    private void SearchPlatformExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPlatformExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SearchPlatformExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main mainMenu = new Main();
                mainMenu.setVisible(true);
                // mainMenu.setSize(500, 500);
                mainMenu.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCompanyClearButton;
    private javax.swing.JButton AddCompanyConfirmButton;
    private javax.swing.JButton AddCompanyExitButton;
    private javax.swing.JLabel AddCompanyMessageLabel;
    private javax.swing.JPanel AddCompanyPanel;
    private javax.swing.JButton AddGameClearButton;
    private javax.swing.JButton AddGameConfirmButton;
    private javax.swing.JButton AddGameExitButton;
    private javax.swing.JLabel AddGameMessageLabel;
    private javax.swing.JPanel AddGameTabPanel;
    private javax.swing.JButton AddPlatformClearButton;
    private javax.swing.JButton AddPlatformConfirmButton;
    private javax.swing.JButton AddPlatformExitButton;
    private javax.swing.JLabel AddPlatformMessageLabel;
    private javax.swing.JPanel AddPlatformTabPanel;
    private javax.swing.JLabel CompanyLocationErrorLabel;
    private javax.swing.JLabel CompanyLocationLabel;
    private javax.swing.JTextField CompanyLocationTextField;
    private javax.swing.JLabel CompanyNameErrorLabel;
    private javax.swing.JLabel CompanyNameLabel;
    private javax.swing.JTextField CompanyNameTextField;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel GameDeveloperErrorLabel;
    private javax.swing.JTextField GameDeveloperTextField;
    private javax.swing.JLabel GameGenreErrorLabel;
    private javax.swing.JTextField GameGenreTextField;
    private javax.swing.JLabel GamePlatformErrorLabel;
    private javax.swing.JTextField GamePlatformTextField;
    private javax.swing.JLabel GamePublisherErrorLabel;
    private javax.swing.JTextField GamePublisherTextField;
    private javax.swing.JLabel GameTitleErrorLabel;
    private javax.swing.JTextField GameTitleTextField;
    private javax.swing.JLabel GameYearOfReleaseErrorLabel;
    private javax.swing.JTextField GameYearOfReleaseTextField;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JTabbedPane MainMenuTabPanel;
    private javax.swing.JLabel PlatformLabel;
    private javax.swing.JLabel PlatformNameErrorLabel;
    private javax.swing.JLabel PlatformNameLabel;
    private javax.swing.JTextField PlatformNameTextField;
    private javax.swing.JLabel PlatformYearOfReleaseErrorLabel;
    private javax.swing.JLabel PlatformYearOfReleaseLabel;
    private javax.swing.JTextField PlatformYearOfReleaseTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton SearchCompanyButton;
    private javax.swing.JButton SearchCompanyExitButton;
    private javax.swing.JLabel SearchCompanyLocationLabel;
    private javax.swing.JTextField SearchCompanyLocationTextField;
    private javax.swing.JLabel SearchCompanyMessageLabel;
    private javax.swing.JLabel SearchCompanyNameLabel;
    private javax.swing.JTextField SearchCompanyNameTextField;
    private javax.swing.JLabel SearchDeveloperLabel;
    private javax.swing.JTextField SearchDeveloperTextField;
    private javax.swing.JLabel SearchGenreLabel;
    private javax.swing.JTextField SearchGenreTextField;
    private javax.swing.JLabel SearchMessageLabel;
    private javax.swing.JButton SearchPlatformButton;
    private javax.swing.JButton SearchPlatformExitButton;
    private javax.swing.JLabel SearchPlatformLabel;
    private javax.swing.JLabel SearchPlatformMessageLabel;
    private javax.swing.JLabel SearchPlatformNameLabel;
    private javax.swing.JTextField SearchPlatformNameTextField;
    private javax.swing.JTextField SearchPlatformTextField;
    private javax.swing.JLabel SearchPlatformYORLabel;
    private javax.swing.JTextField SearchPlatformYORTextField;
    private javax.swing.JLabel SearchPublisherLabel;
    private javax.swing.JTextField SearchPublisherTextField;
    private javax.swing.JPanel SearchTabPanel;
    private javax.swing.JLabel SearchTitleLabel;
    private javax.swing.JTextField SearchTitleTextField;
    private javax.swing.JLabel SearchYearOfReleaseErrorLabel;
    private javax.swing.JLabel SearchYearOfReleaseLabel;
    private javax.swing.JTextField SearchYearOfReleaseTextField;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel YearOfReleaseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
