package GameDatabase;

public class Main extends javax.swing.JFrame {

    SQLController controller;
    
    /**
     * Creates new form TabedMenuFrame
     */
    public Main() {
        initComponents();
        controller = new SQLController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuTabPanel = new javax.swing.JTabbedPane();
        SearchTabPanel = new javax.swing.JPanel();
        AddCompanyPanel = new javax.swing.JPanel();
        CompanyNameLabel = new javax.swing.JLabel();
        CompanyLocationLabel = new javax.swing.JLabel();
        CompanyNameTextField = new javax.swing.JTextField();
        CompanyLocationTextField = new javax.swing.JTextField();
        AddCompanyConfirmButton = new javax.swing.JButton();
        AddCompanyClearButton = new javax.swing.JButton();
        AddCompanyExitButton = new javax.swing.JButton();
        CompanyNameErrorLabel = new javax.swing.JLabel();
        CompanyLocationErrorLabel = new javax.swing.JLabel();
        AddCompanyMessageLabel = new javax.swing.JLabel();
        AddPlatformTabPanel = new javax.swing.JPanel();
        PlatformNameLabel = new javax.swing.JLabel();
        PlatformYearOfReleaseLabel = new javax.swing.JLabel();
        PlatformNameTextField = new javax.swing.JTextField();
        PlatformYearOfReleaseTextField = new javax.swing.JTextField();
        AddPlatformConfirmButton = new javax.swing.JButton();
        AddPlatformClearButton = new javax.swing.JButton();
        AddPlatformExitButton = new javax.swing.JButton();
        PlatformNameErrorLabel = new javax.swing.JLabel();
        PlatformYearOfReleaseErrorLabel = new javax.swing.JLabel();
        AddPlatformMessageLabel = new javax.swing.JLabel();
        AddGameTabPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        PlatformLabel = new javax.swing.JLabel();
        YearOfReleaseLabel = new javax.swing.JLabel();
        GenreLabel = new javax.swing.JLabel();
        GameTitleTextField = new javax.swing.JTextField();
        GamePlatformTextField = new javax.swing.JTextField();
        GameYearOfReleaseTextField = new javax.swing.JTextField();
        GameGenreTextField = new javax.swing.JTextField();
        AddGameConfirmButton = new javax.swing.JButton();
        AddGameClearButton = new javax.swing.JButton();
        AddGameExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GameDeveloperTextField = new javax.swing.JTextField();
        GamePublisherTextField = new javax.swing.JTextField();
        GameTitleErrorLabel = new javax.swing.JLabel();
        GamePlatformErrorLabel = new javax.swing.JLabel();
        GameYearOfReleaseErrorLabel = new javax.swing.JLabel();
        GameGenreErrorLabel = new javax.swing.JLabel();
        GameDeveloperErrorLabel = new javax.swing.JLabel();
        GamePublisherErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Game Database");

        javax.swing.GroupLayout SearchTabPanelLayout = new javax.swing.GroupLayout(SearchTabPanel);
        SearchTabPanel.setLayout(SearchTabPanelLayout);
        SearchTabPanelLayout.setHorizontalGroup(
            SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        SearchTabPanelLayout.setVerticalGroup(
            SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        MainMenuTabPanel.addTab("Search For Game", SearchTabPanel);

        CompanyNameLabel.setText("Name:");

        CompanyLocationLabel.setText("Location:");

        CompanyNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyNameTextFieldActionPerformed(evt);
            }
        });

        CompanyLocationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyLocationTextFieldActionPerformed(evt);
            }
        });

        AddCompanyConfirmButton.setText("Confirm");
        AddCompanyConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCompanyConfirmButtonActionPerformed(evt);
            }
        });

        AddCompanyClearButton.setText("Clear");
        AddCompanyClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCompanyClearButtonActionPerformed(evt);
            }
        });

        AddCompanyExitButton.setText("Exit");
        AddCompanyExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCompanyExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCompanyPanelLayout = new javax.swing.GroupLayout(AddCompanyPanel);
        AddCompanyPanel.setLayout(AddCompanyPanelLayout);
        AddCompanyPanelLayout.setHorizontalGroup(
            AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddCompanyMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                        .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                                .addGap(0, 62, Short.MAX_VALUE)
                                .addComponent(AddCompanyConfirmButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddCompanyClearButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddCompanyExitButton))
                            .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CompanyLocationLabel)
                                    .addComponent(CompanyNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CompanyNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(CompanyLocationTextField))))
                        .addGap(18, 18, 18)
                        .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CompanyNameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CompanyLocationErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap())
        );
        AddCompanyPanelLayout.setVerticalGroup(
            AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyNameLabel)
                    .addComponent(CompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CompanyNameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyLocationLabel)
                    .addComponent(CompanyLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CompanyLocationErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCompanyConfirmButton)
                    .addComponent(AddCompanyClearButton)
                    .addComponent(AddCompanyExitButton))
                .addGap(156, 156, 156)
                .addComponent(AddCompanyMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainMenuTabPanel.addTab("Add Company", AddCompanyPanel);

        PlatformNameLabel.setText("Name:");

        PlatformYearOfReleaseLabel.setText("Year of Release:");

        AddPlatformConfirmButton.setText("Confirm");
        AddPlatformConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatformConfirmButtonActionPerformed(evt);
            }
        });

        AddPlatformClearButton.setText("Clear");
        AddPlatformClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatformClearButtonActionPerformed(evt);
            }
        });

        AddPlatformExitButton.setText("Exit");
        AddPlatformExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatformExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPlatformTabPanelLayout = new javax.swing.GroupLayout(AddPlatformTabPanel);
        AddPlatformTabPanel.setLayout(AddPlatformTabPanelLayout);
        AddPlatformTabPanelLayout.setHorizontalGroup(
            AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                        .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                                .addComponent(AddPlatformConfirmButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddPlatformClearButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddPlatformExitButton))
                            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PlatformYearOfReleaseLabel)
                                    .addComponent(PlatformNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PlatformNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(PlatformYearOfReleaseTextField))))
                        .addGap(18, 18, 18)
                        .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlatformNameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PlatformYearOfReleaseErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                    .addComponent(AddPlatformMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AddPlatformTabPanelLayout.setVerticalGroup(
            AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlatformNameLabel)
                    .addComponent(PlatformNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlatformNameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlatformYearOfReleaseLabel)
                    .addComponent(PlatformYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlatformYearOfReleaseErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddPlatformConfirmButton)
                    .addComponent(AddPlatformClearButton)
                    .addComponent(AddPlatformExitButton))
                .addGap(159, 159, 159)
                .addComponent(AddPlatformMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainMenuTabPanel.addTab("Add Platform", AddPlatformTabPanel);

        TitleLabel.setText("Title:");

        PlatformLabel.setText("Platform:");

        YearOfReleaseLabel.setText("Year of Release:");

        GenreLabel.setText("Genre:");

        AddGameConfirmButton.setText("Confirm");
        AddGameConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGameConfirmButtonActionPerformed(evt);
            }
        });

        AddGameClearButton.setText("Clear");
        AddGameClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGameClearButtonActionPerformed(evt);
            }
        });

        AddGameExitButton.setText("Exit");
        AddGameExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGameExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Developer:");

        jLabel2.setText("Publisher:");

        javax.swing.GroupLayout AddGameTabPanelLayout = new javax.swing.GroupLayout(AddGameTabPanel);
        AddGameTabPanel.setLayout(AddGameTabPanelLayout);
        AddGameTabPanelLayout.setHorizontalGroup(
            AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                        .addComponent(AddGameConfirmButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddGameClearButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddGameExitButton))
                    .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YearOfReleaseLabel)
                            .addComponent(GenreLabel)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GameGenreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(GameYearOfReleaseTextField)
                            .addComponent(GameDeveloperTextField)
                            .addComponent(GamePublisherTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddGameTabPanelLayout.createSequentialGroup()
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleLabel)
                            .addComponent(PlatformLabel))
                        .addGap(63, 63, 63)
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GameTitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(GamePlatformTextField))))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GameTitleErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GamePlatformErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GameYearOfReleaseErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GameGenreErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GameDeveloperErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GamePublisherErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addContainerGap())
        );
        AddGameTabPanelLayout.setVerticalGroup(
            AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleLabel)
                    .addComponent(GameTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GameTitleErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlatformLabel)
                    .addComponent(GamePlatformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GamePlatformErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearOfReleaseLabel)
                    .addComponent(GameYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GameYearOfReleaseErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenreLabel)
                    .addComponent(GameGenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GameGenreErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(GameDeveloperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GameDeveloperErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GamePublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GamePublisherErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddGameConfirmButton)
                    .addComponent(AddGameClearButton)
                    .addComponent(AddGameExitButton))
                .addGap(65, 65, 65))
        );

        MainMenuTabPanel.addTab("Add Game", AddGameTabPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuTabPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuTabPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompanyLocationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyLocationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyLocationTextFieldActionPerformed

    private void CompanyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyNameTextFieldActionPerformed

    private void AddCompanyExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCompanyExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_AddCompanyExitButtonActionPerformed

    private void AddPlatformExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatformExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_AddPlatformExitButtonActionPerformed

    private void AddGameExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGameExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_AddGameExitButtonActionPerformed

    private void AddCompanyClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCompanyClearButtonActionPerformed
        // TODO add your handling code here:
        CompanyNameTextField.setText("");
        CompanyLocationTextField.setText("");
    }//GEN-LAST:event_AddCompanyClearButtonActionPerformed

    private void AddCompanyConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCompanyConfirmButtonActionPerformed
        // TODO add your handling code here:
        String name = CompanyNameTextField.getText();
        String location = CompanyLocationTextField.getText();
        
        if (name.equals(""))
            CompanyNameErrorLabel.setText("required field");
        
        if (location.equals(""))
            CompanyLocationErrorLabel.setText("required field");
        
        if (!name.equals("") && !location.equals(""))
        {
            String message = controller.addCompany(name, location);
            AddCompanyMessageLabel.setText(message);

            CompanyNameTextField.setText("");
            CompanyLocationTextField.setText("");
            CompanyNameErrorLabel.setText("");
            CompanyLocationErrorLabel.setText("");
        }
    }//GEN-LAST:event_AddCompanyConfirmButtonActionPerformed

    private void AddPlatformClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatformClearButtonActionPerformed
        // TODO add your handling code here:
        PlatformNameTextField.setText("");
        PlatformYearOfReleaseTextField.setText("");
    }//GEN-LAST:event_AddPlatformClearButtonActionPerformed

    private void AddPlatformConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatformConfirmButtonActionPerformed
        // TODO add your handling code here:
        String name = PlatformNameTextField.getText();
        
        if (name.equals(""))
            PlatformNameErrorLabel.setText("required field");
        
        int year;
        try{
            year = Integer.parseInt(PlatformYearOfReleaseTextField.getText());
        } catch (NumberFormatException e){
            PlatformYearOfReleaseTextField.setText("");
            PlatformYearOfReleaseErrorLabel.setText(e.getMessage());
            return;
        }
        
        if (!name.equals(""))
        {
            String message = controller.addPlatform(name, year);
            AddPlatformMessageLabel.setText(message);
            
            PlatformNameTextField.setText("");
            PlatformYearOfReleaseTextField.setText("");
            PlatformNameErrorLabel.setText("");
            PlatformYearOfReleaseErrorLabel.setText("");
        }
    }//GEN-LAST:event_AddPlatformConfirmButtonActionPerformed

    private void AddGameClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGameClearButtonActionPerformed
        // TODO add your handling code here:
        GameTitleTextField.setText("");
        GamePlatformTextField.setText("");
        GameYearOfReleaseTextField.setText("");
        GameGenreTextField.setText("");
        GameDeveloperTextField.setText("");
        GamePublisherTextField.setText("");
    }//GEN-LAST:event_AddGameClearButtonActionPerformed

    private void AddGameConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGameConfirmButtonActionPerformed
        // TODO add your handling code here:
        String name = GameTitleTextField.getText();
        String platform = GameTitleTextField.getText();
        int year;
        try {
            year = Integer.parseInt(GameYearOfReleaseTextField.getText());
        } catch (NumberFormatException e){
            GameYearOfReleaseTextField.setText("");
            return;
        }
    }//GEN-LAST:event_AddGameConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main mainMenu = new Main();
                mainMenu.setVisible(true);
                // mainMenu.setSize(500, 500);
                mainMenu.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCompanyClearButton;
    private javax.swing.JButton AddCompanyConfirmButton;
    private javax.swing.JButton AddCompanyExitButton;
    private javax.swing.JLabel AddCompanyMessageLabel;
    private javax.swing.JPanel AddCompanyPanel;
    private javax.swing.JButton AddGameClearButton;
    private javax.swing.JButton AddGameConfirmButton;
    private javax.swing.JButton AddGameExitButton;
    private javax.swing.JPanel AddGameTabPanel;
    private javax.swing.JButton AddPlatformClearButton;
    private javax.swing.JButton AddPlatformConfirmButton;
    private javax.swing.JButton AddPlatformExitButton;
    private javax.swing.JLabel AddPlatformMessageLabel;
    private javax.swing.JPanel AddPlatformTabPanel;
    private javax.swing.JLabel CompanyLocationErrorLabel;
    private javax.swing.JLabel CompanyLocationLabel;
    private javax.swing.JTextField CompanyLocationTextField;
    private javax.swing.JLabel CompanyNameErrorLabel;
    private javax.swing.JLabel CompanyNameLabel;
    private javax.swing.JTextField CompanyNameTextField;
    private javax.swing.JLabel GameDeveloperErrorLabel;
    private javax.swing.JTextField GameDeveloperTextField;
    private javax.swing.JLabel GameGenreErrorLabel;
    private javax.swing.JTextField GameGenreTextField;
    private javax.swing.JLabel GamePlatformErrorLabel;
    private javax.swing.JTextField GamePlatformTextField;
    private javax.swing.JLabel GamePublisherErrorLabel;
    private javax.swing.JTextField GamePublisherTextField;
    private javax.swing.JLabel GameTitleErrorLabel;
    private javax.swing.JTextField GameTitleTextField;
    private javax.swing.JLabel GameYearOfReleaseErrorLabel;
    private javax.swing.JTextField GameYearOfReleaseTextField;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JTabbedPane MainMenuTabPanel;
    private javax.swing.JLabel PlatformLabel;
    private javax.swing.JLabel PlatformNameErrorLabel;
    private javax.swing.JLabel PlatformNameLabel;
    private javax.swing.JTextField PlatformNameTextField;
    private javax.swing.JLabel PlatformYearOfReleaseErrorLabel;
    private javax.swing.JLabel PlatformYearOfReleaseLabel;
    private javax.swing.JTextField PlatformYearOfReleaseTextField;
    private javax.swing.JPanel SearchTabPanel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel YearOfReleaseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}