package GameDatabase;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form TabedMenuFrame
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuTabPanel = new javax.swing.JTabbedPane();
        SearchTabPanel = new javax.swing.JPanel();
        AddCompanyPanel = new javax.swing.JPanel();
        CompanyNameLabel = new javax.swing.JLabel();
        CompanyLocationLabel = new javax.swing.JLabel();
        CompanyNameTextField = new javax.swing.JTextField();
        CompanyLocationTextField = new javax.swing.JTextField();
        AddCompanyConfirmButton = new javax.swing.JButton();
        AddCompanyClearButton = new javax.swing.JButton();
        AddCompanyExitButton = new javax.swing.JButton();
        AddPlatformTabPanel = new javax.swing.JPanel();
        PlatformNameLabel = new javax.swing.JLabel();
        PlatformYearOfReleaseLabel = new javax.swing.JLabel();
        PlatformNameTextField = new javax.swing.JTextField();
        PlatformYearOfReleaseTextField = new javax.swing.JTextField();
        AddPlatformConfirmButton = new javax.swing.JButton();
        AddPlatformClearButton = new javax.swing.JButton();
        AddPlatformExitButton = new javax.swing.JButton();
        AddGameTabPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        PlatformLabel = new javax.swing.JLabel();
        YearOfReleaseLabel = new javax.swing.JLabel();
        GenreLabel = new javax.swing.JLabel();
        AddTitleTextField = new javax.swing.JTextField();
        AddPlatformTextField = new javax.swing.JTextField();
        AddYearOfReleaseTextField = new javax.swing.JTextField();
        AddGenreTextField = new javax.swing.JTextField();
        AddGameConfirmButton = new javax.swing.JButton();
        AddGameClearButton = new javax.swing.JButton();
        AddGameExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Game Database");

        javax.swing.GroupLayout SearchTabPanelLayout = new javax.swing.GroupLayout(SearchTabPanel);
        SearchTabPanel.setLayout(SearchTabPanelLayout);
        SearchTabPanelLayout.setHorizontalGroup(
            SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        SearchTabPanelLayout.setVerticalGroup(
            SearchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        MainMenuTabPanel.addTab("Search For Game", SearchTabPanel);

        CompanyNameLabel.setText("Name:");

        CompanyLocationLabel.setText("Location:");

        CompanyNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyNameTextFieldActionPerformed(evt);
            }
        });

        CompanyLocationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyLocationTextFieldActionPerformed(evt);
            }
        });

        AddCompanyConfirmButton.setText("Confirm");

        AddCompanyClearButton.setText("Clear");

        AddCompanyExitButton.setText("Exit");
        AddCompanyExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCompanyExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCompanyPanelLayout = new javax.swing.GroupLayout(AddCompanyPanel);
        AddCompanyPanel.setLayout(AddCompanyPanelLayout);
        AddCompanyPanelLayout.setHorizontalGroup(
            AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCompanyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddCompanyConfirmButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddCompanyClearButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddCompanyExitButton))
                    .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                        .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompanyLocationLabel)
                            .addComponent(CompanyNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompanyNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(CompanyLocationTextField))))
                .addGap(170, 170, 170))
        );
        AddCompanyPanelLayout.setVerticalGroup(
            AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCompanyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyNameLabel)
                    .addComponent(CompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyLocationLabel)
                    .addComponent(CompanyLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(AddCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCompanyConfirmButton)
                    .addComponent(AddCompanyClearButton)
                    .addComponent(AddCompanyExitButton))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        MainMenuTabPanel.addTab("Add Company", AddCompanyPanel);

        PlatformNameLabel.setText("Name:");

        PlatformYearOfReleaseLabel.setText("Year of Release:");

        AddPlatformConfirmButton.setText("Confirm");

        AddPlatformClearButton.setText("Clear");

        AddPlatformExitButton.setText("Exit");
        AddPlatformExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatformExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPlatformTabPanelLayout = new javax.swing.GroupLayout(AddPlatformTabPanel);
        AddPlatformTabPanel.setLayout(AddPlatformTabPanelLayout);
        AddPlatformTabPanelLayout.setHorizontalGroup(
            AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                        .addComponent(AddPlatformConfirmButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddPlatformClearButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddPlatformExitButton))
                    .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                        .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlatformYearOfReleaseLabel)
                            .addComponent(PlatformNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PlatformNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(PlatformYearOfReleaseTextField))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        AddPlatformTabPanelLayout.setVerticalGroup(
            AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPlatformTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlatformNameLabel)
                    .addComponent(PlatformNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlatformYearOfReleaseLabel)
                    .addComponent(PlatformYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(AddPlatformTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddPlatformConfirmButton)
                    .addComponent(AddPlatformClearButton)
                    .addComponent(AddPlatformExitButton))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        MainMenuTabPanel.addTab("Add Platform", AddPlatformTabPanel);

        TitleLabel.setText("Title:");

        PlatformLabel.setText("Platform:");

        YearOfReleaseLabel.setText("Year of Release:");

        GenreLabel.setText("Genre:");

        AddGameConfirmButton.setText("Confirm");

        AddGameClearButton.setText("Clear");

        AddGameExitButton.setText("Exit");
        AddGameExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGameExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Developer:");

        jLabel2.setText("Publisher:");

        javax.swing.GroupLayout AddGameTabPanelLayout = new javax.swing.GroupLayout(AddGameTabPanel);
        AddGameTabPanel.setLayout(AddGameTabPanelLayout);
        AddGameTabPanelLayout.setHorizontalGroup(
            AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                        .addComponent(AddGameConfirmButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddGameClearButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddGameExitButton))
                    .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YearOfReleaseLabel)
                            .addComponent(GenreLabel)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddGenreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(AddYearOfReleaseTextField)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddGameTabPanelLayout.createSequentialGroup()
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleLabel)
                            .addComponent(PlatformLabel))
                        .addGap(63, 63, 63)
                        .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddTitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(AddPlatformTextField))))
                .addGap(0, 117, Short.MAX_VALUE))
        );
        AddGameTabPanelLayout.setVerticalGroup(
            AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGameTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleLabel)
                    .addComponent(AddTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlatformLabel)
                    .addComponent(AddPlatformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearOfReleaseLabel)
                    .addComponent(AddYearOfReleaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenreLabel)
                    .addComponent(AddGenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(AddGameTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddGameConfirmButton)
                    .addComponent(AddGameClearButton)
                    .addComponent(AddGameExitButton))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        MainMenuTabPanel.addTab("Add Game", AddGameTabPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuTabPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuTabPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompanyLocationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyLocationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyLocationTextFieldActionPerformed

    private void CompanyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyNameTextFieldActionPerformed

    private void AddCompanyExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCompanyExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_AddCompanyExitButtonActionPerformed

    private void AddPlatformExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatformExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_AddPlatformExitButtonActionPerformed

    private void AddGameExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGameExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_AddGameExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMenu mainMenu = new MainMenu();
                mainMenu.setVisible(true);
                // mainMenu.setSize(500, 500);
                mainMenu.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCompanyClearButton;
    private javax.swing.JButton AddCompanyConfirmButton;
    private javax.swing.JButton AddCompanyExitButton;
    private javax.swing.JPanel AddCompanyPanel;
    private javax.swing.JButton AddGameClearButton;
    private javax.swing.JButton AddGameConfirmButton;
    private javax.swing.JButton AddGameExitButton;
    private javax.swing.JPanel AddGameTabPanel;
    private javax.swing.JTextField AddGenreTextField;
    private javax.swing.JButton AddPlatformClearButton;
    private javax.swing.JButton AddPlatformConfirmButton;
    private javax.swing.JButton AddPlatformExitButton;
    private javax.swing.JPanel AddPlatformTabPanel;
    private javax.swing.JTextField AddPlatformTextField;
    private javax.swing.JTextField AddTitleTextField;
    private javax.swing.JTextField AddYearOfReleaseTextField;
    private javax.swing.JLabel CompanyLocationLabel;
    private javax.swing.JTextField CompanyLocationTextField;
    private javax.swing.JLabel CompanyNameLabel;
    private javax.swing.JTextField CompanyNameTextField;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JTabbedPane MainMenuTabPanel;
    private javax.swing.JLabel PlatformLabel;
    private javax.swing.JLabel PlatformNameLabel;
    private javax.swing.JTextField PlatformNameTextField;
    private javax.swing.JLabel PlatformYearOfReleaseLabel;
    private javax.swing.JTextField PlatformYearOfReleaseTextField;
    private javax.swing.JPanel SearchTabPanel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel YearOfReleaseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}